### ISSUE TITLE
Strange behavior of error tracking

### ISSUE THREAD

**Issue by huyparody** [duyquang91/ActivityIndicator#2] opened 2023-05-15 14:08 UTC
I have a simple Login screen, which is called a login API after a button click, but when the API causes an error, the `.trackError(errorIndicator)` has some weird behavior, the API does not call but I keep receive the last error it's ever emitted repeatedly after writing some more text in the text field or click the login button, then I use the `.catch { }` operator, it solves the problem.

Here is my demo source code and video:

[test-activity-indicator.zip](https://github.com/duyquang91/ActivityIndicator/files/11478562/test-activity-indicator.zip)

https://github.com/duyquang91/ActivityIndicator/assets/10293697/6f1d9f7e-ce35-4f06-8390-c0ec6e3ff892

**Comment by duyquang91** [comment] 2023-05-22 02:46
Hi @huyparody, thank for your report. 
I can reproduce the issue from your sample project.
I just figure out if I `sink` the error publisher inside the `ViewModel` then the error publisher still works as expected.
I suppose the `onReceive` method of the `View` in the `SwiftUI` works unexpected, unfortunately I don't have much working experiences with `SwifUI` then I can't debug further. Hope you can help to figure it out from this point.

**Comment by hoc081098** [comment] 2023-06-20 10:00
Every time `ContentView.body` is called, `viewModel.errorPublisher` will return a new Publisher instance (because it is a computed property).

That causes `onReceive(_:perform:)` to cancel the old Publisher and subscribe to the new one. The new one has the same behavior as `ConcurrentValueSubject` (aka. `@Published private var relay: Error?` ~ `replay=1`). So the latest error value is replayed the `ContentView` is rendered.

-> Avoid this by storing the [Lazy Stored Properties](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties/#Lazy-Stored-Properties) that would persist between view re-renders.

```swift
class ViewModel: ObservableObject {
    lazy var errorPublisher: AnyPublisher<Error, Never> = errorIndicator.errors.eraseToAnyPublisher()
}
```

**Comment by duyquang91** [comment] 2023-06-30 17:21
Yeah, you're right @hoc081098, that is how SwiftUI work. I understand that @huyparody get the sample code from README.md, it is my fault, it works perfectly in UIKit where the binding is invoked once, it would be a problem in SwiftUI as demonstrated. I'll update the README.md then.
Suggestion from @hoc081098  is perfect, I just wanna give @huyparody one more approach by using `@Published`
```swift
class ViewModel: ObservableObject {
...
@Published var errors: Errors?
init() {

   errorIndicator.errors
            .sink { error in self.errors = error }
            .store(in: &bag)
   }
...      
}      
```
Now you can use `errors` like other outputs such as `isEnableLoginButton`, it is more friendly with SwiftUI rather than `Publisher`
I'll close the issue, thank guys for the great discussion!

**Closed as completed** 2023-06-30 17:28 UTC
